PL_MVC/Controllers/CargaMasivaController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class CargaMasivaController : Controller
    {
        // GET: CargaMasiva
        public ActionResult Get()
        {

            ML.ResultExcel resultExcel = new ML.ResultExcel();

            return View(resultExcel);

        }


        [HttpPost]
        public ActionResult Get(int? dato)
        {


            // Validar la extensión del archivo
            if (Session["PathArchivo"] == null)
            {
                HttpPostedFileBase file = Request.Files["ArchivoExcel"];
                string pathFolder = ConfigurationManager.AppSettings["pathFolder"].ToString();

                if (file.ContentLength > 0)
                {
                    string extensionArchivo = Path.GetExtension(file.FileName).ToLower();
                    string extensionModulo = ConfigurationManager.AppSettings["TipoExcel"].ToString();

                    if (extensionArchivo == extensionModulo)
                    {
                        string pathArchivo = Server.MapPath(pathFolder) + Path.GetFileNameWithoutExtension(file.FileName) + '-' + DateTime.Now.ToString("yyyyMMddHHmmss") + ".xlsx";
                        if (!System.IO.File.Exists(pathArchivo))
                        {
                            file.SaveAs(pathArchivo);
                            string connectionString = ConfigurationManager.AppSettings["ConnectionStringExcel"].ToString() + pathArchivo;
                            var resultPaquetes = BL.Paquete.CargaMasivaExcel(connectionString);

                            if (resultPaquetes.Item1)
                            {
                                // Aquí obtienes los paquetes
                                var result =  resultPaquetes.Item3;
                                // Asegúrate de que los paquetes sean válidos antes de pasarlos a la vista
                                if (result != null && result.Any())
                                {
                                    // Si los paquetes son válidos, puedes guardar la ruta del archivo en la sesión
                                    Session["PathArchivo"] = pathArchivo;
                                    // Y luego pasas los paquetes a la vista
                                    return View(new ML.ResultExcel() { Paquetes = result });
                                }
                                else
                                {
                                    ViewBag.Text = "El archivo no contiene paquetes válidos.";
                                    return PartialView("Modal");
                                }
                            }
                            else
                            {
                                //ViewBag.Text = "El excel no contiene registros en las Fila ni Columna";
                                //return PartialView("Modal");
                                return View(new ML.ResultExcel());
                            }
                        }
                    }
                    else
                    {
                        ViewBag.Text = "Favor de seleccionar un archivo .xlsx, Verifique su archivo";
                        return PartialView("Modal");
                    }
                }
                else
                {
                    ViewBag.Mensaje = "No selecciono ningun archivo, Seleccione uno correctamente";
                }
                return View();
            }
            else
            {
                // Si la sesión existe, se omite la validación y se agregan los paquetes a la base de datos
                string pathArchivo = Session["PathArchivo"].ToString();
                string connectionString = ConfigurationManager.AppSettings["ConnectionStringExcel"].ToString() + pathArchivo;

                // Proceso de lectura del archivo Excel y obtención de los datos
                var datos = BL.Paquete.CargaMasivaExcel(connectionString);

                if (datos.Item1)
                {
                    // Si se cargaron los datos exitosamente del archivo Excel
                    foreach (ML.Paquete paquete in datos.Item3)
                    {
                        // Agregar cada paquete a la base de datos
                        BL.Paquete.AddEF(paquete);
                    }

                    // Limpiar la sesión
                    Session["PathArchivo"] = null;

                    // Mostrar mensaje de éxito

                    //ViewBag.Text = "Exitoso";
                    //return PartialView("Modal");
                    return View(new ML.ResultExcel());
                }
                else
                {
                    // Si hubo algún problema al cargar los datos del archivo Excel
                    //ViewBag.Text = "Hubo un error al cargar los paquetes desde el archivo Excel.";
                    //return PartialView("Modal");
                    return View(new ML.ResultExcel());
                }
            }
        }

    }
}






        //[HttpPost]
        //public ActionResult CargaTXT()
        //{
        //    HttpPostedFileBase file = Request.Files["ArchivoTXT"];

        //    if (file != null)
        //    {
        //        if (file.ContentLength > 0)
        //        {
        //            string extension = Path.GetExtension(file.FileName).ToLower();

        //            if (extension == ".txt")
        //            {
        //                string pathFolder = "~/CargaMasiva/";
        //                string pathArchivo = Server.MapPath(pathFolder) + Path.GetFileNameWithoutExtension(file.FileName) + "-" + DateTime.Now.ToString("yyyyMMddhhmmss") + ".txt";

        //                if (!System.IO.File.Exists(pathArchivo))
        //                {
        //                    file.SaveAs(pathArchivo);



        //                    return PartialView("Modal");
        //                }
        //            }
        //        }
        //    }

        //    return View();
        //}

    

PL_MVC/Views/CargaMasiva/Get.cshtml
@model ML.ResultExcel

@{
    ViewBag.Title = "Get";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h1 class="text-center">Subir Archivos</h1>

<div class="row">
    <div class="col-md-6">
        <div class="container">
            <div style="background-color: #067cd8; padding: 10px; margin-bottom: 10px;">
                <p class="text-center text-ginda mb-0" style="font-size: 24px;">Archivo Excel</p>
            </div>
            @using (Html.BeginForm("Get", "CargaMasiva", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <input type="file" id="archivoInput" name="ArchivoExcel" />
                <input type="submit" id="procesarBtn" value="Procesar" />
            }
        </div>
    </div>
    @if (Model.Errores != null && Model.Errores.Count > 0)
    {
        <div>
           <table class="table">
               <tr>
                   <td>IdRegistro</td>
                   <td>Mensaje</td>
               </tr>
               @foreach (var resultado in Model.Errores)
               {
                   <tr class="text-center">
                       <td>@resultado.IdRegistro</td>
                       <td>@resultado.Mensaje</td>
                   </tr>
               }
           </table>
        </div>
    }
    else
    {

        if (Model.Paquetes.Count > 0)
        {
            <div>
                <h2>Detalles de Paquetes</h2>
                <table class="table">
                    <thead>
                        <div style="background-color: green; padding: 10px; margin-bottom: 10px;">
                            <p class="text-center text-ginda mb-0" style="font-size: 24px;">Todo ha salido bien</p>
                        </div>
                        <tr>
                            <th>Instrucción de Entrega</th>
                            <th>Peso</th>
                            <th>Dirección de Origen</th>
                            <th>Dirección de Entrega</th>
                            <th>Fecha Estimada de Entrega</th>
                            <th>Número de Guía</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var paquete in Model.Paquetes)
                        {
                            <tr>
                                <td>@paquete.InstruccionEntrega</td>
                                <td>@paquete.Peso</td>
                                <td>@paquete.DireccionOrigen</td>
                                <td>@paquete.DireccionEntrega</td>
                                <td>@paquete.FechaEstimadaEntrega</td>
                                <td>@paquete.NumeroGuia</td>
                            </tr>

                               
                            
                        }
                    </tbody>
                </table>
            </div>
        }
    }
</div>

@*<script>
    $(document).ready(function () {
        // Deshabilitar el input de archivo y cambiar el valor del botón al cargar la página si el archivo ya se ha subido
        var archivoSubido = '@Session["PathArchivo"]';
        if (archivoSubido) {
            $('#archivoInput').prop('disabled', true);
            $('#procesarBtn').val('Guardar');
        }

        // Cambiar el valor del botón y deshabilitar el input de archivo cuando se envía el formulario
        $('form').submit(function () {
            $('#archivoInput').prop('disabled', true);
            $('#procesarBtn').val('Guardar');
        });

        // Manejar el clic en el botón "Guardar"
        $('#procesarBtn').click(function () {
            var archivoSubido = '@Session["PathArchivo"]';
            if (archivoSubido) {
                // Aquí puedes llamar a una función JavaScript para procesar los registros del archivo Excel y agregarlos a la base de datos
                // Ejemplo:
                $.ajax({
                    url: '@Url.Action("Get", "CargaMasiva")',
                    type: 'POST',
                    data: { archivo: archivoSubido },
                    success: function (response) {
                        // Manejar la respuesta, por ejemplo, mostrar un mensaje de éxito
                        alert('Registros guardados exitosamente.');
                        // Puedes redirigir a otra página después de guardar los registros si es necesario
                    },
                    error: function () {
                        // Manejar el error, por ejemplo, mostrar un mensaje de error
                        alert('Error al guardar los registros.');
                    }
                });
            } else {
                // Si no se ha subido ningún archivo
 </script>*@

PL_MVC/Views/CargaMasiva/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4> @*Titulo del Modal*@
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Text</h5> @*Contenido del Modal*@
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Vale", "CargaMasi", "CargaMasiva", htmlAttributes: new { @class = "btn btn-danger" }) @*boton para dirigir a la vista que queramos*@
            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>