PL_MVC/Controllers/EnvioPaquetesController.cs
using BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class EnvioPaquetesController : Controller
    {
        public ActionResult EnviarPaquetes()
        {
            if (Session["Asignar"] == null)
            {
                ML.AsignacionPaqueteRepartidor asignar = new ML.AsignacionPaqueteRepartidor();
                asignar.Asignaciones = new List<ML.AsignacionPaqueteRepartidor>();

                return View(asignar);
            }
            else
            {
                ML.AsignacionPaqueteRepartidor asignar = new ML.AsignacionPaqueteRepartidor();
                asignar.Asignaciones = new List<ML.AsignacionPaqueteRepartidor>();
                asignar.Asignaciones = (List<ML.AsignacionPaqueteRepartidor>)Session["Asignar"];
                return View(asignar);
            }
        }

        [HttpPost]
        public ActionResult AddToSession(ML.AsignacionPaqueteRepartidor asignarAdd)
        {


            if (asignarAdd.Repartidor == null || asignarAdd.Repartidor.IdRepartidor == 0)
            {
                ViewBag.Text = "Es necesario elegir un repartidor";
                return PartialView("Modal");
            }

            bool exists = false;

                ML.AsignacionPaqueteRepartidor asignar = new ML.AsignacionPaqueteRepartidor();
                asignar.Asignaciones = new List<ML.AsignacionPaqueteRepartidor>();
                asignar.Paquete = new ML.Paquete();
                asignar.Repartidor = new ML.Repartidor();


                var result = BL.Paquete.GetByIdLINQ(asignarAdd.Paquete.IdPaquete);
                var resultRepatidor = BL.Repartidor.GetById(asignarAdd.Repartidor.IdRepartidor);


                asignar.Paquete = result.Item3;
                asignar.Repartidor = resultRepatidor.Item3;
                BL.AsignacionPaqueteRepartidor.AddEF(asignarAdd.Paquete.IdPaquete, asignarAdd.Repartidor.IdRepartidor);
                if (Session["Asignar"] == null)
                {
                    asignar.TotalPaquetes = 1;
                    asignar.Asignaciones.Add(asignar);

                    Session["Asignar"] = asignar.Asignaciones;
                    //BL.AsignacionPaqueteRepartidor.AddEF(asignarAdd.Repartidor.IdRepartidor, asignarAdd.Paquete.IdPaquete);

                }
                else
                {
                    GetAsignar(asignar);
                    foreach (ML.AsignacionPaqueteRepartidor paquete in asignar.Asignaciones)
                    {
                        if (asignarAdd.Repartidor.IdRepartidor == paquete.Repartidor.IdRepartidor)
                        {
                            paquete.TotalPaquetes++;
                            exists = true;
                            break;
                        }
                        else
                        {
                            exists = false;
                        }
                    }
                    if (exists)
                    {
                        Session["Asignar"] = asignar.Asignaciones;
                    }
                    else
                    {
                        asignar.TotalPaquetes = 1;
                        asignar.Asignaciones.Add(asignar);
                        Session["Asignar"] = asignar.Asignaciones;
                    }
                }      

            ViewBag.Text = "Asignacion correcta";
            return PartialView("Modal");
            //return RedirectToAction("GetAll", "Paquete");
        }

          
        public ML.AsignacionPaqueteRepartidor GetAsignar(ML.AsignacionPaqueteRepartidor asignar)
        {
            List<ML.AsignacionPaqueteRepartidor> asignacion = (List<ML.AsignacionPaqueteRepartidor>)Session["Asignar"];

            foreach(var obj in asignacion)
            {
                asignar.Asignaciones.Add(obj);
            }
            return asignar;
        }



        [HttpPost]
        public ActionResult IncremetarPaquetes(int repartidorId)
        {
            var asignacion = (List<ML.AsignacionPaqueteRepartidor>)Session["Asignar"];
            if (asignacion != null)
            {
                // Encuentra la asignación correspondiente al repartidorId
                var asignar = asignacion.FirstOrDefault(a => a.Repartidor.IdRepartidor == repartidorId);
                if (asignar != null)
                {
                    // Aumenta la cantidad de paquetes asignados al repartidor en la base de datos
                    var result = BL.AsignacionPaqueteRepartidor.ModificarCatidad(repartidorId, 1);
                    if (result.Item1)
                    {
                        // Si la operación en la base de datos es exitosa, aumenta la cantidad de paquetes en la sesión
                        asignar.TotalPaquetes++;
                        Session["Asignar"] = asignacion;

                        // Redirige a una vista de éxito
                        ViewBag.Text = "Asignacion correcta";
                        return PartialView("Modal");
                    }
                    else
                    {
                        // Si la operación en la base de datos falla, redirige a una vista de error
                        return View("Error");
                    }
                }
            }

            // Si no se encuentra la asignación, o no hay asignaciones en la sesión, redirige a una vista de error
            return View("Error");
        }




        [HttpPost]
        public ActionResult DisminuirPaquetes(int repartidorId)
        {
            var asignacion = (List<ML.AsignacionPaqueteRepartidor>)Session["Asignar"];
            if (asignacion != null)
            {
                // Encuentra la asignación correspondiente al repartidorId y disminuye la cantidad de paquetes
                var asignar = asignacion.FirstOrDefault(a => a.Repartidor.IdRepartidor == repartidorId);
                if (asignar != null)
                {
                    var result = BL.AsignacionPaqueteRepartidor.ModificarCatidad(repartidorId, -1);
                    asignar.TotalPaquetes--;

                    // Si la cantidad de paquetes llega a cero, se elimina la asignación de la lista
                    if (asignar.TotalPaquetes <= 0)
                    {
                        asignacion.Remove(asignar);
                    }
                }
                Session["Asignar"] = asignacion;
            }

            // retornar indicador de éxito 
            return Json(new { success = true });
        }


    }
}

PL_MVC/Controllers/PaquetesController.cs
using ML;
using PL_MVC.ServiceReferencePaquete;
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Net.Http;
using System.Security.Cryptography.X509Certificates;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls.WebParts;


namespace PL_MVC.Controllers
{
    public class PaquetesController : Controller
    {

        //---------------------------------GetAll--------------------------------------------------------------------------------------------
        // GET: Paquetes
        //public ActionResult GetAll()
        //{
        //    var result = BL.Paquete.GetAllClient();
        //    var resultd = BL.Repartidor.GetAllEF();




        //        if (result.Item1 == true)
        //        {
        //            ML.Paquete paquete1 = new ML.Paquete();
        //            paquete1.paqueteLista = result.Item3;

        //            //Asignar la lista de repartidores al modelo Paquete
        //            paquete1.Repartidor = new ML.Repartidor();
        //            paquete1.Repartidor.Repartidores = resultd.Item3;

        //            return View(paquete1);


        //        }
        //        else
        //        {   //manda la lista de paquetes
        //            ML.Paquete paquete = new ML.Paquete();
        //            return View();
        //        }
        //    }
        //----------------------webapi-------------------------------------

        //public ActionResult GetAll()
        //    //WebService
        //{
        //    //var result = BL.Paquete.GetAllClient();
        //    var resultd = BL.Repartidor.GetAllEF();

        //    using (HttpClient client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri("https://localhost:44327/api/");
        //        var responseTask = client.GetAsync("paquete/GetAll");
        //        responseTask.Wait();

        //        var result = responseTask.Result;

        //        if (result.IsSuccessStatusCode)
        //        {
        //            var readTask = result.Content.ReadAsAsync<List<ML.Paquete>>();

        //            readTask.Wait();

        //            if(readTask.Result != null)
        //            {
        //                ML.Paquete paquete1 = new ML.Paquete();
        //                paquete1.paqueteLista = readTask.Result;

        //                paquete1.Repartidor = new ML.Repartidor();
        //                paquete1.Repartidor.Repartidores = resultd.Item3;

        //                return View(paquete1);

        //            }
        //            else
        //            {   //manda la lista de paquetes
        //                ML.Paquete paquete = new ML.Paquete();
        //                return View();
        //            }
        //        }

        //        return View();   

        //    }         

        //}

        //------------------------------------GetAll con WCF-----------------------------------------------------------------------------------------

        public ActionResult GetAll()
        //WebService
        {
            //var result = BL.Paquete.GetAllClient();
            var resultd = BL.Repartidor.GetAllEF();

            ServiceReferencePaquete.IPaquetes client = new ServiceReferencePaquete.PaquetesClient();



            var resultado = client.GetAll();
            if (resultado.Item1)
            {
                ML.Paquete paquete = new ML.Paquete();
                paquete.paqueteLista = resultado.Item3.ToList();

                paquete.Repartidor = new Repartidor();
                paquete.Repartidor.Repartidores = resultd.Item3.Repartidores;
                //paquete.Repartidor.Repartidores = resultd.Item3.tolis;

                return View(paquete);

            }

            return View();

        }

        //------------------------------------getbyid-----------------------------------------------------------------------------------------

        //[HttpGet]
        //public ActionResult Form(int? idPaquete)
        //{
        //    //intancear el modelo de paquete
        //    ML.Paquete paquete = new ML.Paquete();
        //    //instancear la lista de paquetes (Trae sus propiedades)
        //    List<ML.Paquete> paqueteLis = new List<ML.Paquete>();

        //    if (idPaquete != null)
        //    {
        //        //para mandar llamar a lo registro para editar por el id
        //        var resultPaquete = BL.Paquete.GetByIdLINQ(idPaquete.Value);
        //        paquete = resultPaquete.Item3;

        //        var resultadoPaquete = BL.Paquete.GetAllClient();
        //        paquete.paqueteLista = new List<ML.Paquete>();
        //        paqueteLis = resultadoPaquete.Item3;
        //        paquete.paqueteLista = paqueteLis;
        //        paquete.paqueteLista = resultadoPaquete.Item3;

        //        return View(paquete);

        //    }
        //    else
        //    {
        //        var resultado = BL.Paquete.GetAllClient();
        //        paquete.paqueteLista = new List<ML.Paquete>();
        //        paqueteLis = resultado.Item3;
        //        paquete.paqueteLista = paqueteLis;

        //        return View(paquete);
        //    }

        //}


        //----------------------webapi-------------------------------------
        //[HttpGet]
        ////Esto es para el WebService
        //public ActionResult Form(int? idPaquete)
        //{
        //    //intancear el modelo de paquete
        //    ML.Paquete paquete = new ML.Paquete();
        //    //instancear la lista de paquetes (Trae sus propiedades)
        //    List<ML.Paquete> paqueteLis = new List<ML.Paquete>();

        //    if (idPaquete != null)
        //    {
        //        //para mandar llamar a lo registro para editar por el id
        //        //var resultPaquete = BL.Paquete.GetByIdLINQ(idPaquete.Value);
        //        using (HttpClient client = new HttpClient())
        //        {
        //            client.BaseAddress = new Uri("https://localhost:44327/api/");
        //            var responseTask = client.GetAsync("paquete/GetById?IdPaquete= " + idPaquete);
        //            responseTask.Wait();

        //            var result = responseTask.Result;
        //            if (result.IsSuccessStatusCode)
        //            {
        //                var resultadoPaquete = BL.Paquete.GetAllClient();
        //                paquete.paqueteLista = new List<ML.Paquete>();
        //                paqueteLis = resultadoPaquete.Item3;
        //                paquete.paqueteLista = paqueteLis;
        //                paquete.paqueteLista = resultadoPaquete.Item3;

        //                return View(paquete);

        //            }
        //            else
        //            {
        //                var resultado = BL.Paquete.GetAllClient();
        //                paquete.paqueteLista = new List<ML.Paquete>();
        //                paqueteLis = resultado.Item3;
        //                paquete.paqueteLista = paqueteLis;

        //                return View(paquete);
        //            }
        //        }

        //    }
        //    return View(paquete);

        //}

        //------------------------------------GetByid con WCF-----------------------------------------------------------------------------------------

        [HttpGet]
        //Esto es para el WebService
        public ActionResult Form(int? idPaquete)
        {
            //intancear el modelo de paquete
            ML.Paquete paquete = new ML.Paquete();
            //instancear la lista de paquetes (Trae sus propiedades)
            List<ML.Paquete> paqueteLis = new List<ML.Paquete>();

            if (idPaquete != null)
            {
                //para mandar llamar a lo registro para editar por el id

                ServiceReferencePaquete.IPaquetes client = new ServiceReferencePaquete.PaquetesClient();
                var resultado = client.GetById(idPaquete.Value);

                var resultadoPaquete = BL.Paquete.GetAllClient();
                paquete.paqueteLista = new List<ML.Paquete>();
                paqueteLis = resultadoPaquete.Item3;
                paquete.paqueteLista = paqueteLis;
                paquete.paqueteLista = resultadoPaquete.Item3;

                return View(paquete);

            }
            else
            {
                var resultado = BL.Paquete.GetAllClient();
                paquete.paqueteLista = new List<ML.Paquete>();
                paqueteLis = resultado.Item3;
                paquete.paqueteLista = paqueteLis;

                return View(paquete);



            }


        }



        //------------------------------------ADD y Update con webApi-----------------------------------------------------------------------------------------

        //[HttpPost]
        //public ActionResult Form(ML.Paquete paquete)

        //{
        //    //si es diferente de nulo el registro que enviare a editar que se cumpla la condicion para editarlo
        //    if (paquete.IdPaquete != 0)
        //    {
        //        //  variable donde se guardata el registro, luego llamar a mi gunvion editar de mi modelo y madarle mi parametro

        //        //var resultado = BL.Paquete.UpdateEF(paquete);

        //        //if (resultado.Item1)

        //        using (HttpClient client = new HttpClient())
        //        {
        //            client.BaseAddress = new Uri("https://localhost:44327/api/");
        //            var responseTask = client.PutAsJsonAsync<ML.Paquete>("paquete/update", paquete);
        //            responseTask.Wait();

        //            var result = responseTask.Result;

        //            if (result.IsSuccessStatusCode)
        //            {

        //                ViewBag.Text = "La actualizacion fue Exitosa";

PL_MVC/Views/EnvioPaquetes/EnviarPaquetes.cshtml
@model ML.AsignacionPaqueteRepartidor

@{
    ViewBag.Title = "EnviarPaquetes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2 class="text-center">Enviar Paquetes</h2>

<div style="text-align: right;">
    <a href="@Url.Action("GetAll", "Paquetes")" float-right" id="btnRegresar">
        <img src="~/Imagen/devolver.png" style="width: 40px; height: 40px;" />
    </a>
</div>
<br />



@if (Model.Asignaciones.Any(paquete => paquete.TotalPaquetes > 0))
{
    <table class="table table-hover table-bordered border border-primary border-3">
        <thead>
            <tr class="table-secondary">
                <th class="text-center">Añadir paquete</th>
                <th class="text-center">Cantidad de paquetes</th>
                <th class="text-center">Quitar paquete</th>
                <th class="text-center">Instrucción de Entrega</th>
                <th class="text-center">Número de guía</th>
                <th class="text-center">Datos del repartidor</th>
                <th class="text-center">Fecha y Dirección de entrega</th>
            </tr>
        </thead>
        <tbody>
            @foreach (ML.AsignacionPaqueteRepartidor paquete in Model.Asignaciones.Where(paquete => paquete.TotalPaquetes > 0))
            {
                <tr class="text-center align-middle">
                    <td><button class="plus-button" onclick="IncremetarPaquetes('@paquete.Repartidor.IdRepartidor')" style="background-color: #89BCB0;"></button></td>
                    <td>@paquete.TotalPaquetes</td>
                    <td><button class="minus-button" onclick="DisminuirPaquetes('@paquete.Repartidor.IdRepartidor')" style="background-color: #89BCB0;"></button></td>
                    <td>@paquete.Paquete.InstruccionEntrega</td>
                    <td>@paquete.Paquete.NumeroGuia</td>
                    <td>@paquete.Repartidor.Nombre @paquete.Repartidor.ApellidoPaterno @paquete.Repartidor.ApellidoPMaterno</td>
                    <td>@paquete.Paquete.FechaEstimadaEntrega, @paquete.Paquete.DireccionEntrega </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{



    @*<div style="background-color: #AF3333; padding: 10px; margin-bottom: 10px; ">
        <p class="text-center  mb-0" style="font-size: 24px; color: black;">No hay paquetes disponibles!!</p>
    </div>*@

    <div style="text-align: center; position: relative;">
        <img src="~/Imagen/ojo.png" alt="Imagen" style="width: 80px; height: auto;">
        <div class="cloud">
            <p style="color: aquamarine">"No hay ningún paquete que visualizar"</p>
        </div>
    </div>
}









<script>
    function IncremetarPaquetes(repartidorId) {
        $.ajax({
            url: '@Url.Action("IncremetarPaquetes", "EnvioPaquetes")',
            type: 'POST',
            data: { repartidorId: repartidorId },
            success: function (result) {
                // Manejar el éxito si es necesario
                location.reload(); // Recargar la página por ejemplo
            },
            error: function (xhr, status, error) {
                console.log(error);
            }
        });
    }
</script>

<script>
    function DisminuirPaquetes(repartidorId) {
        $.ajax({
            url: '@Url.Action("DisminuirPaquetes", "EnvioPaquetes")',
            type: 'POST',
            data: { repartidorId: repartidorId },
            success: function (result) {
                // Manejar el éxito si es necesario
                location.reload(); // Recargar la página por ejemplo
            },
            error: function (xhr, status, error) {
                console.log(error);
            }
        });
    }
</script>

@*Imgenes para los botones*@

<style>
    .plus-button {
        background-color: white;
        background-image: url('/Imagen/agregar.png');
        background-size: cover;
        width: 40px; /* Ajusta el ancho y alto de acuerdo a tu imagen */
        height: 40px;
        border: none;
        cursor: pointer;
    }
</style>

<style>
    .minus-button {
        background-color: white;
        background-image: url('/Imagen/menos.png');
        background-size: cover;
        width: 40px; /* Ajusta el ancho y alto de acuerdo a tu imagen */
        height: 40px;
        border: none;
        cursor: pointer;
    }
</style>

<style>
    body {
        background-color: #89BCB0; /* Color de fondo deseado */
    }

    /*Este estilo es para el mesaje de cuando no hay ningun paquete agregado a la vista */
    .cloud {
        position: absolute;
        top: -40px; /* Ajusta la posición vertical de la nube */
        left: 50%;
        transform: translateX(-50%);
        background-color: #AF3333;
        padding: 10px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
    }

        .cloud p {
            margin: 0;
        }
</style>

PL_MVC/Views/EnvioPaquetes/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4> @*Titulo del Modal*@
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Text</h5> @*Contenido del Modal*@
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Vale", "EnviarPaquetes", "EnvioPaquetes", htmlAttributes: new { @class = "btn btn-danger" }) @*boton para dirigir a la vista que queramos*@
            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>