PL_MVC/Controllers/ServicioClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class ServicioClienteController : Controller
    {
        // GET: ServicioCliente
        public ActionResult ServicioACliente()
        {
            // Mostrar la vista sin ningún modelo de paquete
            return View();
        }

        [HttpPost]
        public ActionResult ServicioACliente(string NumeroGuia)
        {
            // Verificar si se proporciona un código válido
            if (!string.IsNullOrEmpty(NumeroGuia))
            {
                // Intentar buscar el paquete por el código proporcionado
                var resultado = BL.Paquete.GetByNumeroGuia(NumeroGuia);

                if (resultado.Item1)
                {
                    // Si se encuentra el paquete, mostrar la vista con el paquete encontrado
                    return View("Principal", resultado.Item3);
                }
            }

            // Si no se proporciona un código válido o si no se encuentra el paquete, mostrar la vista sin ningún modelo de paquete
            return View("Principal");
        }

        public ActionResult PreguntasFrecuentes()
        {
           
            return View();
        }



        [HttpPost]
        public ActionResult EnviarCorreo(string name, string email, string subject, string message)
        {
            // Llamamos al método para enviar el correo electrónico
            EnviarCorreoElectronico(name, email, subject, message);

            // Redireccionamos a una página de agradecimiento o a donde desees
            ViewBag.Text = "Se envio con exito";
            return PartialView("Modal");
        }

       

        private void EnviarCorreoElectronico(string name, string email, string subject, string message)
        {
            try
            {
                // Configuración del correo electrónico
                string destinatario = "willmen99@gmail.com";
                string cuerpoMensaje = $"Nombre: {name}\n" +
                                       $"Correo Electrónico: {email}\n" +
                                       $"Asunto: {subject}\n\n" +
                                       $"Mensaje:\n{message}";

                // Crear objeto de correo electrónico
                MailMessage correo = new MailMessage(email, destinatario, subject, cuerpoMensaje);

                // Configurar cliente SMTP
                SmtpClient clienteSmtp = new SmtpClient("smtp.gmail.com")
                {
                    Port = 587,
                    Credentials = new NetworkCredential("willmen99@gmail.com", "rklkzaahmfffssql"),
                    EnableSsl = true
                };

                // Enviar correo electrónico
                clienteSmtp.Send(correo);
            }
            catch (Exception ex)
            {
                // Manejo de errores, puedes registrar el error en el sistema de registro o manejarlo de otra manera
                // Aquí puedes agregar código para manejar el error de manera adecuada
                throw new Exception("Error al enviar correo electrónico.", ex);
            }
        }

    }
}
    

PL_MVC/Views/ServicioCliente/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4> @*Titulo del Modal*@
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Text</h5> @*Contenido del Modal*@
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Vale", "ServicioACliente", "ServicioCliente", htmlAttributes: new { @class = "btn btn-danger" }) @*boton para dirigir a la vista que queramos*@
            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PL_MVC/Views/ServicioCliente/PreguntasFrecuentes.cshtml
@{
    ViewBag.Title = "PreguntasFrecuentes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h1 style="text-align: center; color: #005a8d; font-size: 50px;">
    <strong>Preguntas frecuentes</strong>
</h1>

<h2 style="text-align: center; color:black ">para rastreo y seguimiento</h2>
<br />
<br />

<!-- Pregunta 1 -->
<p id="clickable1" style="cursor:  pointer; color: blue; text-decoration: underline; text-align:center;">
    ¿Qué es un número de rastreo y dónde puedo encontrarlo?
</p>
<p id="info1" style="display: none; text-align: center;">
    Un número de rastreo es un código único utilizado para seguir el progreso de un envío. Puedes encontrarlo en el recibo de tu envío o en el correo electrónico de confirmación de tu pedido.
</p>
<hr style="border-top: .5px solid #333333; margin-top: 20px; margin-bottom: 20px;">



<!-- Pregunta 2 -->
<p id="clickable2" style="cursor: pointer; color: blue; text-decoration: underline; text-align: center;">
    ¿Cuándo estará disponible la información de rastreo?
</p>
<p id="info2" style="display: none; text-align: center;">
    La información de rastreo estará disponible tan pronto como el envío sea procesado por la empresa de transporte. Esto puede variar dependiendo del servicio y la empresa de mensajería utilizada.
</p>
<hr style="border-top: .5px solid #333333; margin-top: 20px; margin-bottom: 20px;">




<!-- Pregunta 3 -->
<p id="clickable3" style="cursor: pointer; color: blue; text-decoration: underline; text-align: center;">
    ¿Por qué no funciona mi número de rastreo o ID de rastreo?
</p>
<p id="info3" style="display: none; text-align: center; ">
    Hay varias razones por las cuales un número de rastreo o ID puede no funcionar, como errores en la entrada del número, retrasos en la actualización del sistema de seguimiento, o problemas con el servicio de mensajería. Te recomendamos verificar el número e intentarlo nuevamente más tarde.
</p>
<hr style="border-top: .5px solid #333333; margin-top: 20px; margin-bottom: 20px;">



<!-- Pregunta 4 -->
<p id="clickable4" style="cursor: pointer; color: blue; text-decoration: underline; text-align: center;">
    ¿Puedo rastrear mi envío si no tengo un número de rastreo?
</p>
<p id="info4" style="display: none; text-align:center">
    En la mayoría de los casos, necesitarás un número de rastreo para seguir el progreso de tu envío. Sin embargo, algunos servicios de mensajería ofrecen opciones alternativas de seguimiento basadas en la información de tu cuenta o dirección de envío. Te recomendamos ponerte en contacto con el servicio de atención al cliente para obtener más información.
</p>
<hr style="border-top: .5px solid #333333; margin-top: 20px; margin-bottom: 20px;">
<br />
<br />
<br />
<!-- Script JavaScript -->
<script>
    // Función para mostrar u ocultar la información cuando se hace clic
    function toggleInfo(clickableId, infoId) {
        const clickableElement = document.getElementById(clickableId);
        const infoElement = document.getElementById(infoId);

        clickableElement.addEventListener('click', () => {
            infoElement.style.display = (infoElement.style.display === 'none') ? 'block' : 'none';
        });
    }

    // Llamar a la función para cada pregunta
    toggleInfo('clickable1', 'info1');
    toggleInfo('clickable2', 'info2');
    toggleInfo('clickable3', 'info3');
    toggleInfo('clickable4', 'info4');
</script>







<div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; text-align: center;">
    <!-- Enlaces rápidos -->
    <div>
        <h3>Enlaces rápidos</h3>
        <ul style="list-style-type: none; padding: 0;">
            <li><a href="http://localhost:60964/ServicioCliente/ServicioACliente">Servicio al Cliente</a></li>
            <li><a href="http://localhost:60964/Login/Login">Portal de Inicios de Sesión del Cliente</a></li>
            <li><a href="#">Socios digitales e integraciones</a></li>
            <li><a href="#">Portal del Desarrollador</a></li>
            <li><a href="#">Obtenga una cotización</a></li>
            <li><a href="#">DHL para Empresas</a></li>
        </ul>
    </div>

    <!-- Nuestras Divisiones -->
    <div>
        <h3>Nuestras Divisiones</h3>
        <ul style="list-style-type: none; padding: 0;">
            <li><a href="#">DHL Express</a></li>
            <li><a href="#">DHL Global Forwarding</a></li>
            <li><a href="#">DHL Supply Chain</a></li>
            <li><a href="#">Otras Divisiones Globales</a></li>
        </ul>
    </div>

    <!-- Sectores de la Industria -->
    <div>
        <h3>Sectores de la Industria</h3>
        <ul style="list-style-type: none; padding: 0;">
            <li><a href="#">Movilidad Autónoma</a></li>
            <li><a href="#">Productos Químicos</a></li>
            <li><a href="#">Consumidor</a></li>
            <li><a href="#">Energía</a></li>
            <li><a href="#">Ingeniería y Fabricación</a></li>
            <li><a href="#">Ciencias Biológicas y Sector de la Salud</a></li>
            <li><a href="#">Sector Público</a></li>
            <li><a href="#">Retail</a></li>
            <li><a href="#">Tecnología</a></li>
        </ul>
    </div>

    <!-- Información de la Empresa -->
    <div>
        <h3>Información de la Empresa</h3>
        <ul style="list-style-type: none; padding: 0;">
            <li><a href="#">Acerca de DHL</a></li>
            <li><a href="#">Entregado</a></li>
            <li><a href="#">Carreras</a></li>
            <li><a href="#">Centro de Prensa</a></li>
            <li><a href="#">Inversores</a></li>
            <li><a href="#">Sustentabilidad</a></li>
            <li><a href="#">Ideas e Innovación</a></li>
            <li><a href="#">Asociaciones de marca</a></li>
        </ul>
    </div>

</div>



<!-- Link de bootstrap para importa los iconono de social media -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet">

<!-- Iconos de redes sociales -->
<div style="text-align:center; margin-top: 50px;">
    <h6>Síguenos</h6>
    <ul class="social-icons" style="list-style-type: none; padding: 0; display: flex; justify-content: center;">
        <li style="margin-right: 30px;"><a href="#"><i class="bi bi-facebook"></i></a></li>
        <li style="margin-right: 30px;"><a href="#"><i class="bi bi-twitter"></i></a></li>
        <li style="margin-right: 30px;"><a href="#"><i class="bi bi-instagram"></i></a></li>
        <li style="margin-right: 30px;"><a href="#"><i class="bi bi-linkedin"></i></a></li>
        <li><a href="#"><i class="bi bi-youtube"></i></a></li>
    </ul>
</div>

<style>
    .social-icons i {
        font-size: 24px; /* Cambia este valor según lo grande que desees los iconos */
    }
</style>




@*<footer>
        <p style="text-align:center;">© 2024 Tu Proyecto de Envío de Paquetes. Todos los derechos reservados.</p>
    </footer>*@

PL_MVC/Views/ServicioCliente/ServicioACliente.cshtml
@{
    ViewBag.Title = "ServicioACliente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h1 style="margin-left: -30px; color: #005a8d "> <strong>Servicio al Cliente</strong></h1>
<br />
<br />

<div style="display: flex; justify-content: flex-end;">
    <div class="container1" style="margin-left: 0px">
        <div class="additional-information">
            <blockquote class="blockquote" style="font-size: 20px;">
                <p class="mb-0"><strong>¿Tiene un número de rastreo? Encuentre su contacto</strong></p>
            </blockquote>

            <div class="col-md-6">
                <form action="@Url.Action("Principal", "Principal")" method="post">
                    <div class="input-group mb-md-4">
                        <input type="text" class="form-control" name="NumeroGuia" placeholder="Ingresa el número de rastreo" style="font-size: 15px;" required>

                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit" id="btnBuscarPaquete">Rastrear</button>
                        </div>
                    </div>
                </form>
            </div>
            <ul>
                <p><strong>Su número de rastreo nos permite encontrar su paquete con todos los datos</strong></p>
                <li style="margin-left: 30px;">Rastreo en tiempo real de tus paquetes</li>
                <li style="margin-left: 30px;">Datos adiconales de cada paquete, (Dirección,QR,Descripción, etc)</li>
                <li style="margin-left: 30px;">Mapa de dirección del paquete,(Origen y Entrega) </li>
                @*<li style="margin-left: 30px;">Opciones de envío exprés</li>*@
            </ul>
            <hr style="border-top: .5px solid #333333; margin-top: 20px; margin-bottom: 20px;">
            <ul>
                <p><strong>¿No tiene número de rastreo?</strong></p>
                <li style="margin-left: 30px;"><a href=http://localhost:60964/Paquetes/GetAll>Ver mi numero de Guia</a></li>
                <li style="margin-left: 30px;"><a href=http://localhost:60964/ServicioCliente/PreguntasFrecuentes>Vea todas las Preguntas Frecuentes sobre el Rastreo </a></li>

            </ul>
        </div>
    </div>

    <div class="container2" style="margin-right: 50px; margin-top: 50px;">

        <div class="additional-information2">
            <blockquote class="blockquote" style="font-size: 10px;">
                <p class="mb-0"><strong>¿Tiene un número de rastreo? Encuentre su contacto</strong></p>
            </blockquote>

            <div class="col-md-6">
                <form action="@Url.Action("Principal", "Principal")" method="post">
                    <div class="input-group mb-md-4">
                        <input type="text" class="form-control" name="NumeroGuia" placeholder="Ingresa el número de rastreo" style="font-size: 15px;" required>

                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit" id="btnBuscarPaquete">Rastrear</button>
                        </div>
                    </div>
                </form>
            </div>
            <ul>
                <p><strong>Su número d</strong></p>
                <li style="margin-left: 30px;">Rastro</li>
                @*<li style="margin-left: 30px;">Datos </li>
                <li style="margin-left: 30px;">Mapa</li>*@
                @*<li style="margin-left: 30px;">Opciones de envío exprés</li>*@
            </ul>
            <hr style="border-top: .5px solid #333333; margin-top: 10px; margin-bottom: 10px;">
            <ul>
                <p><strong>¿No tiene número de rastreo?</strong></p>
                <li style="margin-left: 30px;"><a href=http://localhost:60964/Paquetes/GetAll>Ver mi numero de Guia</a></li>
                @*<li style="margin-left: 30px;"><a href=http://localhost:60964/ServicioCliente/PreguntasFrecuentes>Vea todas las Preguntas Frecuentes sobre el Rastreo </a></li>*@

            </ul>
        </div>
    </div>

    <!--<div class="container2" style="margin-right: 50px; margin-bottom: 120px;">

        <div class="additional-information2">
            <blockquote class="blockquote" style="font-size: 10px;">
                <p class="mb-0"><strong>¿Tiene un número de rastreo? Encuentre su contacto</strong></p>
            </blockquote>

            <div class="col-md-6">
                <form action="@Url.Action("Principal", "Principal")" method="post">
                    <div class="input-group mb-md-4">
                        <input type="text" class="form-control" name="NumeroGuia" placeholder="Ingresa el número de rastreo" style="font-size: 15px;" required>

                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit" id="btnBuscarPaquete">Rastrear</button>
                        </div>
                    </div>
                </form>
            </div>
            <ul>
                <p><strong>Su número d</strong></p>
                <li style="margin-left: 30px;">Rastro</li>-->
                @*<li style="margin-left: 30px;">Datos </li>
                <li style="margin-left: 30px;">Mapa</li>*@
                @*<li style="margin-left: 30px;">Opciones de envío exprés</li>*@
            <!--</ul>
            <hr style="border-top: .5px solid #333333; margin-top: 20px; margin-bottom: 20px;">
            <ul>
                <p><strong>¿No tiene número de rastreo?</strong></p>
                <li style="margin-left: 30px;"><a href=http://localhost:60964/Paquetes/GetAll>Ver mi numero de Guia</a></li>-->
                @*<li style="margin-left: 30px;"><a href=http://localhost:60964/ServicioCliente/PreguntasFrecuentes>Vea todas las Preguntas Frecuentes sobre el Rastreo </a></li>*@

            <!--</ul>
        </div>
    </div>-->
</div>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #d6eafa;
            margin: 0;
            padding: 0;
        }

        .container1 {
            max-width: 800px;
            margin: 0 auto;
            padding: initial;
        }

        header h1 {
            color: #005a8d;
            text-align: center;
        }

        .main-content {
            display: flex;
            justify-content: space-between;
        }

        .customer-service-info {
            flex: 1;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .additional-information {
            flex: 1;
            background-color: #f5f7f9;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

            .additional-information h2 {
                color: #005a8d;
                text-align: center;
            }
    </style>


    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #d6eafa;
            margin: 0;
            padding: 0;
        }

        .container2 {
            max-width: 400px;
            max-height: 100px; /* Cambiar la altura según sea necesario */
            margin: 0 auto;
            padding: 0px;
        }

        header h1 {
            color: #005a8d;
            text-align: center;
        }

        .main-content {
            display: flex;
            justify-content: space-between;
        }

        .customer-service-info {
            flex: 1;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .additional-information2 {
            flex: 1;
            background-color: #f5f7f9;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

            .additional-information2 h2 {
                color: #005a8d;
                text-align: center;
            }
    </style>


    <style>
        footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ccc;
        }
    </style>





    @*-----------------------------------------------------------FORMULARIO ATENCION A CLIENTE------------------------------------------------------------------------------------*@

    <head>
        <meta charset="utf-8">
        <title>Servicio al Cliente</title>

        <!-- Font Awesome -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    </head>

    <body>
        <!-- Navbar Start -->
        <div class="container-fluid p-0 nav-bar">

        </div>

        <div class="container-fluid page-header mb-5 position-relative overlay-bottom">

        </div>


        <div class="container-fluid pt-5 pb-3 bg-light">
            <div class="container">
                <div class="section-title text-center">
                    <h2 class="text-primary text-uppercase mb-4">Servicio al Cliente</h2>
                    <p class="text-muted">¡Estamos aquí para ayudarte! Contáctanos si tienes alguna pregunta o comentario sobre nuestros servicios.</p>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <div class="contact-item text-center bg-white p-4 mb-4">
                            <i class="fa fa-map-marker-alt fa-2x mb-3 text-primary"></i>
                            <h4 class="font-weight-bold">Nuestra Ubicación</h4>
                            <p>Av. Paseo de la Reforma 199, Col. Renacimiento, CP. 06500, Alcaldía Cuauhtémoc, CDMX.</p>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="contact-item text-center bg-white p-4 mb-4">
                            <i class="fa fa-phone-alt fa-2x mb-3 text-primary"></i>
                            <h4 class="font-weight-bold">Teléfono</h4>
                            <p>52 66 34 50</p>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="contact-item text-center bg-white p-4 mb-4">
                            <i class="far fa-envelope fa-2x mb-3 text-primary"></i>
                            <h4 class="font-weight-bold">Correo Electrónico</h4>
                            <p>contacto@digis01.com</p>
                        </div>
                    </div>
                </div>

                <div class="row">

                    <!-- Columna del mapa -->
                    <div class="col-lg-6">
                        <!-- Mapa de Google Maps con las coordenadas proporcionadas -->
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3762.583973248309!2d-99.1638359850792!3d19.43036174685038!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d1f8ce0443ffff%3A0xef8b65afe38ede75!2sDigis01%20Soluciones%20Digitales!5e0!3m2!1sen!2smx!4v1630481707862!5m2!1sen!2smx" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                    </div>

                    <div class="col-lg-6">
                        <div class="contact-form bg-white p-4">
                            <h3 class="text-center mb-4">¡Contáctanos!</h3>
                            <form id="contactForm" action="@Url.Action("EnviarCorreo", "ServicioCliente")" method="post" novalidate>
                                <div class="form-group">
                                    <input type="text" class="form-control" id="name" name="name" placeholder="Tu Nombre" required>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control" id="email" name="email" placeholder="Tu Correo Electrónico" required>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" id="subject" name="subject" placeholder="Asunto" required>
                                </div>
                                <div class="form-group">
                                    <textarea class="form-control" rows="5" id="message" name="message" placeholder="Mensaje" required></textarea>
                                </div>
                                <br />
                                <button type="submit" class="btn btn-outline-primary">Enviar Mensaje</button>
                            </form>
                        </div>
                    </div>


                </div>

            </div>
        </div>


        <!-- Footer End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>

    </body>



    <script>
        $(document).ready(function () {
            $('#contactForm').submit(function (event) {
                event.preventDefault(); // Evitar que se envíe el formulario de forma predeterminada

                // Obtener los datos del formulario
                var formData = $(this).serialize();

                // Enviar los datos al método EnviarCorreo del controlador
                $.post($(this).attr('action'), formData, function (data) {
                    // Manejar la respuesta si es necesario
                    // Por ejemplo, mostrar un mensaje de éxito o redirigir a una página de agradecimiento
                });
            });
        });
    </script>




    @*<footer>
            <p>&copy; @DateTime.Now.Year Tu Proyecto de Envío de Paquetes. Todos los derechos reservados.</p>
        </footer>*@